[GLOBAL]
pants_version = "2.25.0"

backend_packages.add = [
  "pants.backend.python",
]

[source]
root_patterns = ["/"]

[python]
enable_resolves = true
resolves = { python-default = "python-default.lock"}
interpreter_constraints = ["==3.12.4"]

[python.resolves_to_interpreter_constraints]
python-default = ["==3.11.*", "==3.12.4"]

